version: '2'

services:

  community-nacos:
    image: nacos/nacos-server
    container_name: community-nacos
    restart: always
    networks:
      community-net:
    external_links:
      - community-mysql:mysql
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=xietong123
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - /data/nacos-server/logs/:/home/nacos/logs
    ports:
      - 8848:8848

  community-redis:
    image: redis
    container_name: community-redis
    networks:
      community-net:
    ports:
      - 6379:6379

  community-mysql:
    image: mysql
    container_name: community-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      community-net:
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xietong123

networks:
  community-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24
          gateway: 192.168.201.1
